version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pip install -r requirements.txt
          name: Test
  run-and-pray:
    executor: python/default
    steps:
      - run:
          command: python -m unittest  discover tests
          name: Run

workflows:
  main:
    jobs:
     docker:
      - image: circleci/python:3.6.2-stretch-browsers
      - run: pip install -r requirements.txt
      - run-and-pray
